### ISSUE TITLE
Documentation for the Netlist Format

### ISSUE THREAD

**Issue by esonghori** [google-research/circuit_training#12]
We use `tensorflow.GraphDef` [protobuffer](https://developers.google.com/protocol-buffers) format to represent netlists. The documentation for the format is not included in the repo.

**Comment by AzoresCabbage** [comment]
Great job. Maybe the documentation can provide descriptions about the API of plc_wrapper_main and more information on SOFT_MACRO? e.g. when to define a MACRO as SOFT_MACRO.

And would you like to release a sample that contains STDCELL?

**Comment by esonghori** [comment]
+1 I've create #14

**Comment by esonghori** [comment]
The following commit addresses this issue

https://github.com/google-research/circuit_training/commit/18d57367c4a9128c8b8ea93c5427114ecc8c03ea
