### ISSUE TITLE
Could you tell me a function?

### ISSUE THREAD

**Issue by yangbo19** [google-research/circuit_training#15]
![e8b3a1e1e9e85223306a79a63e91e8f](https://user-images.githubusercontent.com/95022180/160330466-e095f595-438f-439f-bde3-3ae8575c321a.png)
How do you get the cost through wirelength and area?
Thank you!

**Comment by Gaoustcer** [comment]
add wirelength,congestion and Density together,you will get the result

**Comment by esonghori** [comment]
See [cost_info_function](https://github.com/google-research/circuit_training/blob/b16f0f668d079414c52d4b54d215dc5fa3563179/circuit_training/environment/environment.py#L59) for how cost is calculated.
