### ISSUE TITLE
What is the "weight" attribute in the pb.txt input file?

### ISSUE THREAD

**Issue by Dinple** [google-research/circuit_training#22]
As stated in the title, I am not sure what is the weight attribute. I believe it is only mentioned in the ariane test case. Is it the edge weight between groups or is it something else?

**Comment by choltz95** [comment]
As a quick follow-up, this has been addressed in the new documentation:
https://github.com/google-research/circuit_training/blob/main/docs/NETLIST_FORMAT.md

Thanks a lot for the info!
