### ISSUE TITLE
plc_client.py behavior

### ISSUE THREAD

**Issue by Dinple** [google-research/circuit_training#26]
Hi,

It appears to me that `plc_client` is not fully open-sourced. However, I don't fully understand its behaviour. It seems to me that it is trying to establish some socket connection to a tempfile and retrieve function returns from that socket connection. 

Is it connected to some Google-end server or some binary file on the host machine?

**Comment by sguada** [comment]
As the [Installation](https://github.com/google-research/circuit_training/issues/26) instruction detailed you need to download the `plc_wrapper_main` binary and then provide its path to [`plc_client`](https://github.com/google-research/circuit_training/blob/main/circuit_training/environment/plc_client.py)
