### ISSUE TITLE
Potential bug in getting blockages

### ISSUE THREAD

**Issue by Dinple** [google-research/circuit_training#37]
Hi,

I think there is some minor issue with [get_blockages_from_comments](https://github.com/google-research/circuit_training/blob/83fe7210ba9518c467a59fa0eb5cd3bd6cace551/circuit_training/environment/placement_util.py#L106). Function header allows the filename to be either a string or a list of string, but the actual function definition treats string as a list nonetheless.

If you run placement_util_test.py, you will fail to extract blockage information and get something like this:
![Screenshot from 2022-08-31 09-51-58](https://user-images.githubusercontent.com/24643892/187737479-be24cfde-5afe-473c-a941-c7f0eb8abe3f.png)

This is potentially an issue for [create_placement_cost_using_common_arguments](https://github.com/google-research/circuit_training/blob/83fe7210ba9518c467a59fa0eb5cd3bd6cace551/circuit_training/environment/placement_util.py#L751) since it passes a string to retrieve blockages. This function is also used in grouper.py.

Could you please confirm this? Thanks in advance!

**Comment by esonghori** [comment]
Thanks for pointing this bug out, I'll send a fix shortly.

**Comment by esonghori** [comment]
https://github.com/google-research/circuit_training/commit/d5e454e5bcd153a95d320f664af0d1b378aace7b should fix the issue.
