### ISSUE TITLE
How to use this code with less computing resource?

### ISSUE THREAD

**Issue by KeLiu1998** [google-research/circuit_training#45]
Hi,

I have a question about circuit training for Araine RISC-V, in the guidance you have provided. You used a lot of computing resources including 20 96vCPUs and 8xV100 GPUs, however we do not have that much computing resources,  is that means we can not get a reasonable training result(episode return increase with training process) like you have presented in your tensorboard? If we can get a good training result with our server configuration, would you please tell us how to adjust hyperparameters in your source code, thanks!

**Comment by tfboyd** [comment]
You need a lot of CPUs to generate all of the training data. There is nothing currently that you can do about that. If you had less agents, then the system would just take longer to get the data needed for each iteration.
