### ISSUE TITLE
Information on Dataset

### ISSUE THREAD

**Issue by Mrinal18** [google-research/circuit_training#6]
if we want to reproduce the results, from where should we take the data from? there is no such information present in README.

**Comment by tfboyd** [comment]
https://github.com/google-research/circuit_training/blob/main/docs/ARIANE.md

This covers the step-by-step that we did on google cloud to get the results training from scratch for the Ariane chip.

**Comment by Mrinal18** [comment]
Hello, @tfboyd thank you so much for the information, can you also suggest from where you extracted the dataset/macros? because Ariane RISC-V open source github link is outdated (According to this [issue](https://github.com/riscv-software-src/riscv-tools/issues/333))
