### ISSUE TITLE
How to deepcopy an instance of PlacementCost?

### ISSUE THREAD

**Issue by NJUer211300063** [google-research/circuit_training#61]
How to deepcopy an instance of PlacementCost?

**Comment by NJUer211300063** [comment]
![image](https://github.com/google-research/circuit_training/assets/105654000/0dcf39c8-b34b-4e90-b75d-f322ba341cd7)
When i deepcopy an instance of PlacementCost（self.plc_list = [deepcopy(self.plc) for _ in range(self.pop_size)]）, it raised a error in the picture above.

**Comment by esonghori** [comment]
PlacementCost doesn't support deepcopy. However, you can create multiple copies of the same PlacementCost using its constructor. Also, please note that the only state in the PlacementCost is the location of the nodes, so if you want to copy the state, you need to read the locations from one PlacementCost and apply it to other for all nodes.
